version: '3.8'

services:
    server:
        build:
            context: ./packages/server
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        environment:
            NODE_ENV: development

    frontend:
        build:
            context: ./packages/frontend # Path to your frontend Dockerfile
            dockerfile: Dockerfile
        ports:
            - '3000:80' # Map port 80 inside the container to port 3000 on the host
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
